"""initial

Revision ID: 7c1e51057d00
Revises: 
Create Date: 2025-12-09 15:21:55.754568

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1e51057d00'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accesses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accesses_name'), ['name'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=True)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_name'), ['name'], unique=False)

    op.create_table('access_resources',
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['accesses.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('access_id', 'resource_id')
    )
    op.create_table('conflicts',
    sa.Column('group_id1', sa.Integer(), nullable=False),
    sa.Column('group_id2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id1'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['group_id2'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id1', 'group_id2')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_group_id1'), ['group_id1'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_group_id2'), ['group_id2'], unique=False)

    op.create_table('group_accesses',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['accesses.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'access_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_accesses')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_group_id2'))
        batch_op.drop_index(batch_op.f('ix_conflicts_group_id1'))

    op.drop_table('conflicts')
    op.drop_table('access_resources')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_name'))
        batch_op.drop_index(batch_op.f('ix_resources_id'))

    op.drop_table('resources')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.drop_table('groups')
    with op.batch_alter_table('accesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accesses_name'))
        batch_op.drop_index(batch_op.f('ix_accesses_id'))

    op.drop_table('accesses')
    # ### end Alembic commands ###

